### ISSUE TITLE
Crossbasis for an incomplete series

### ISSUE THREAD

**Issue by ZhengyuEddy** [gasparrini/dlnm#10]
Hi Antonio,

In the crossbasis, x must be a complete series. What if some observations are missing? Are we still able to establish a DLNM?

**Comment by gasparrini** [comment]
Dear YZYEDDI,

as explained on the help page of crossbasis(), the first argument 'x' should be a time series of equally-spaced and complete observations, or alternatively a matrix of exposure histories with rows representing complete lagged exposure for each observation.
Missing observations must be included (as missing), asthe series must be complete. Bear in mind that for any missing observation many missings can be produced in the transformed variables, due to the lagging.

I hope this helps.

best
-Antonio Gasparrini

**Comment by YZYEDDY** [comment]
Thank you for the quick response. This is helpful.

Zhengyu (Eddy) Yang
Climate, Air Quality Research Unit, Monash University
