### ISSUE TITLE
Seeking advice for dlm modelling

### ISSUE THREAD

**Issue by zhihu3456** [gasparrini/dlnm#13]
Dear Professor Antonio Gasparrini,    

I am a new learner of package dlnm. Your function in the dlnm package has greatly simplified our modeling process.       

Recently I found a possible issue: the coef/vcov from reduced coef/vcov(overall effect) and non-reduced coef/vcov could reconstruct exposure-response curve with a noticeable offset after the second-stage meta-analysis when we model an distributed lag linear crossbasis. When modelling an distributed lag non linear crossbasis, the difference could be little in the eye reivew. 

<img width="760" alt="Snipaste_2024-06-17_11-44-25" src="https://github.com/gasparrini/dlnm/assets/154651548/0f164b33-971c-46c3-a551-cb133d83843e">

If this issue is indeed present, do you have any recommendations on which kind of cofe/vcov we should choose for the second-stage modeling?

Best regards,
Zhihu

**Comment by gasparrini** [comment]
Thanks for your interest.
The two processes are different, and some differences can be expected.
In the first option you discard the info in the first stage by reducing, while in the second you are meta-analysing the whole thing. The pooling therefore includes different sets of information.

If you are not interested in assessing the lag structure, I suggest using the reduction.

Best

Antonio Gasparrini, BSc Mbiol MSc PhD
-------------------------------
Professor of Biostatistics and Epidemiology
Lead of the Environment & Health Modelling (EHM) Lab<http://lshtm.ac.uk/ehm-lab>
Co-Director of the Centre for Data and Statistical Science for Health (DASH)<https://www.lshtm.ac.uk/dash>
Department of Public Health Environments & Society
London School of Hygiene & Tropical Medicine
15-17 Tavistock Place, London WC1H 9SH, UK
Website: www.ag-myresearch.com<http://www.ag-myresearch.com/>

From: zhihu xu ***@***.***>
Sent: Monday, June 17, 2024 2:53 AM
To: gasparrini/dlnm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gasparrini/dlnm] Seeking advice for dlm modelling (Issue #13)


Dear Professor Antonio Gasparrini,

I am a new learner of package dlnm. Your function in the dlnm package has greatly simplified our modeling process.

Recently I found a possible issue: the coef/vcov from reduced coef/vcov(overall effect) and non-reduced coef/vcov could reconstruct exposure-response curve with a noticeable offset after the second-stage meta-analysis when we model an distributed lag linear crossbasis. When modelling an distributed lag non linear crossbasis, the difference could be little in the eye reivew.
Snipaste_2024-06-17_11-44-25.png (view on web)<https://github.com/gasparrini/dlnm/assets/154651548/0f164b33-971c-46c3-a551-cb133d83843e>

If this issue is indeed present, do you have any recommendations on which kind of cofe/vcov we should choose for the second-stage modeling?

Best regards,
Zhihu

**Comment by zhihu3456** [comment]
Dear Professor Antonio Gasparrini,

Thank you for your guidance!

Best regards,
Zhihu
